.github/workflows/build-push-multi-arch.yml

- #3 
I'm adding here support for multiple image tags, for example if you want to tag an image with a version and `latest`, you can just provide `image_tags: 22.04,latest`.
Estimated Time of Review: 5 minutes

Support multiple tags in build-push workflow

---

.github/workflows/build-push-multi-arch.yml

- #7 
This PR solves the issue by making the two inputs optional and moving them after the required inputs.
I propose to tag the main branch as v0.1 after this PR such that we can use tags in the other repos
Estimated Time of Review: 3 minutes

Set build context and dockerfile inputs to optional

---

guidelines/AICA_IDEA_CPP_STYLE.xml
guidelines/CPP_STYLE_GUIDE.md

- aica-technology/control-libraries#94
I adjusted the guide that I originally wrote for [LASA](https://github.com/epfl-lasa/wiki/wiki/CPP-Style-Guide-and-Recommendations) and updated it to company standards. I also added my matching CLion style schema XML.
Estimated Time of Review: 15 minutes
One small change I made to the XML, compared to the original I hosted on LASA: I finally found the (well hidden) setting for spacing around the range-based iteration operator. (`SPACE_BEFORE_COLON_IN_FOREACH`)
```c++
// before
for (auto a: b) {
...
}
// after
for (auto a : b) {
...
}
```
If you don't already have it, I suggest you re-import this XML to CLion to make sure we all have the same version.

AICA C++ Style Guide and XML Schema

---

.github/actions/docker-tag-from-git/action.yml

Required for some internal builds (dse, modulo-controlers, api, etc).
Internal PRs

feat(ci): add a new action to choose tag for Docker

---

.github/actions/docker-build-multi/action.yml
.github/actions/docker-build/action.yml
.github/actions/ghcr-build/action.yaml
.github/actions/ghcr-manifest-merge/action.yml

`v0.6.0` breaks when using `docker-build` due to a faulty `image_hash` which has been removed (as currently unused).
Estimated Time of Review: 1 minutes

fix(gha): remove unused and faulty image_hash

---

.github/actions/check-artifact-hash/action.yml
.github/actions/save-artifact-hash/action.yml

This PR adds an action that checks if an artifact that contains the latest hash of a directory exists. It can be reused in dynamic components (https://github.com/aica-technology/dynamic-components/pull/302) and hardware collections (https://github.com/aica-technology/hardware-collections/pull/74) to check if a component/collection needs rebuilding or not.
Estimated Time of Review: 3 minutes
- https://github.com/aica-technology/hardware-collections/pull/74
- https://github.com/aica-technology/dynamic-components/pull/302

Add check artifact hash action

---

.github/actions/git-tag/action.yml

Resolves issue in HC with a failing tag action

feat(gh): add a new action to create git tags

---

.github/actions/git-tag/action.yml

Fix issue in HC around release
Estimated Time of Review: 1 minute

fix(gh): make git-tag less error-prone by checking if the tag exist before pushing

---

guidelines/.clang-format

As we are moving away from clion, we need a `.clang-format` file to format our C++ code. Note that I started by exporting our CLion config as .clang-format, which was quite off from our current style. Hence, I tweaked this file a bit myself and now, the formatting looks (almost) the same. I guess if there are major things that we are not happy with, we can come back to this file and tweak it again. I didn't go through all the code we have... :smile: 
Estimated Time of Review: 3 minutes

chore: add .clang-format file for cpp style

---

.github/pull_request_template.md
README.md
guidelines/CHANGELOG_STYLE_GUIDE.md
guidelines/COMMIT_STYLE_GUIDE.md

- #27 
* Style guide for commits and changelogs
* Update Pull Request template to include commit types and a reminder for checking the changelog
Based on the internal document
https://docs.google.com/document/d/1GUrDjrsIKKdITggBc_hKmhN63wA5hmw0U9DLIh8QC2Y/edit?usp=sharing
Estimated Time of Review: 5 minutes

docs: style guides for commits and changelogs

---

.github/actions/check-version/action.yml

This PR adds an action that can compare the version tags between `package.xml` files from the previous commit with the current commit on the current branch. For that, it stores the previous package file in the tmp folder and reuses other actions to parse the version tag. Afterwards, the action also checks that the version has been changed correctly.
This can be used anywhere, where we will add workflows triggered by pushes on main to check if the image needs to be rebuilt.
Estimated Time of Review: 5 minutes

feat: add check-version action

---

.github/actions/check-version/action.yml

Annoying little mistake...
Estimated Time of Review: 1.1 minutes

fix: input name in check version action

---

.github/actions/parse-package-xml/action.yml

This PR adds a new output (hyphenated name) for the parse-package-xml action

feat: add hyphenated name output

---

.github/actions/check-version/action.yml
.github/actions/compare-versions/action.yml

- #34 
This PR solves the issue by moving the relevant code snippet into its own action so it can be reused in other places, for example
- https://github.com/aica-technology/modulo/pull/58
- https://github.com/aica-technology/api/issues/57
Estimated Time of Review: 5 minutes

feat: add action to check if version changed correctly

---

.github/actions/parse-package-toml/action.yml

fix(parse-package-toml): use a different method to invoke yq which allows to use any folder

---

.github/actions/release-tag-from-toml/action.yml

Add a TOML variation to `get-auto-release-tag`

feat(release-tag-from-toml): add new action to get a release tag from aica-package.toml

---

.github/actions/check-version-toml/action.yml

Otherwise the first release of a package will always fail.

fix(check-version-toml): handle non-existing toml files when comparing version

---

profile/README.md

Update top-level readme with new links
This quick fix updates the links that are visible on the top-level organization page with the .github README file.

docs: update README.md

---

guidelines/CHANGELOG_STYLE_GUIDE.md

Quick fix prompted by a comment from @bpapaspyros to clarify the order and format of changelog entries.

docs: update CHANGELOG_STYLE_GUIDE.md

---

.github/actions/compare-versions/action.yml

This PR changes the `compare-versions` action to allow and verify `-rcX` suffixes to the versions. This should for example allow to release modulo as 5.0.0-rc1 and then commit to it as 5.0.0.
Estimated Time of Review: x minutes

feat: handle release candidate versions

---

.github/actions/compare-versions/action.yml

Small mistake here :(
Estimated Time of Review: 1.1 minutes

fix: output of compare version action

---

.github/actions/check-version-toml/action.yml

fix(check-version-toml): use printf instead of echo
